name: IMTIYAZ-RAJPUT
services:
  - name: imtiyaz-rajput-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin

